/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 14:52:06 GMT 2024
 */

package Controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Controller.ControladorArtigo;
import Model.Vintage;
import View.Apresentacao;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ControladorArtigo_ESTest extends ControladorArtigo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("L");
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      Apresentacao apresentacao0 = new Apresentacao();
      Vintage vintage0 = new Vintage();
      // Undeclared exception!
      try { 
        controladorArtigo0.registarTShirt(apresentacao0, vintage0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      Apresentacao apresentacao0 = new Apresentacao();
      SystemInUtil.addInputLine("PREMIUM");
      Vintage vintage0 = new Vintage();
      // Undeclared exception!
      try { 
        controladorArtigo0.registarSapatilha(apresentacao0, vintage0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      SystemInUtil.addInputLine("PREMIUM");
      Vintage vintage0 = new Vintage();
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      // Undeclared exception!
      try { 
        controladorArtigo0.registarMala(apresentacao0, vintage0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      Vintage vintage0 = new Vintage();
      // Undeclared exception!
      try { 
        controladorArtigo0.registarTShirt((Apresentacao) null, vintage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorArtigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      Vintage vintage0 = new Vintage();
      // Undeclared exception!
      try { 
        controladorArtigo0.registarSapatilha((Apresentacao) null, vintage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorArtigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      // Undeclared exception!
      try { 
        controladorArtigo0.registarMala((Apresentacao) null, (Vintage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorArtigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Apresentacao apresentacao0 = new Apresentacao();
      Vintage vintage0 = new Vintage();
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      // Undeclared exception!
      try { 
        controladorArtigo0.interpretador(apresentacao0, vintage0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ControladorArtigo controladorArtigo0 = new ControladorArtigo();
      Vintage vintage0 = new Vintage();
      // Undeclared exception!
      try { 
        controladorArtigo0.interpretador((Apresentacao) null, vintage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Controller.ControladorArtigo", e);
      }
  }
}
