/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 20:31:30 GMT 2024
 */

package com.marketplace.vintage.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.marketplace.vintage.utils.AlphanumericGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AlphanumericGenerator_ESTest extends AlphanumericGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = AlphanumericGenerator.isOfFormat("@-rOA{a3goLYm(1Z{", "|<?|R@0@[>Yw6^x5k~");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = AlphanumericGenerator.isOfFormat("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", "sb,");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = AlphanumericGenerator.generateAlphanumericCode("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        AlphanumericGenerator.isOfFormat((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.marketplace.vintage.utils.AlphanumericGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        AlphanumericGenerator.generateAlphanumericCode((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.marketplace.vintage.utils.AlphanumericGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      boolean boolean0 = AlphanumericGenerator.isOfFormat("DX:t2lQ\"3d", "DX:t2lQ\"3d");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      boolean boolean0 = AlphanumericGenerator.isOfFormat("DX:t2lQ\"3d", "ABCEF;HIJKLNOaQRSVWXYz013467");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      boolean boolean0 = AlphanumericGenerator.isOfFormat("ABCEF;HIJKLNOaQRSVWXYz013467", "ABCEF;HIJKLNOaQRSVWAYz013467");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String string0 = AlphanumericGenerator.generateAlphanumericCode("ABCEF;HIJKLNOaQRSVWXYz013467");
      assertEquals("ABCEF;HIJKLNOaQRSVWAYz013467", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      AlphanumericGenerator alphanumericGenerator0 = new AlphanumericGenerator();
  }
}
