/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 21:11:29 GMT 2024
 */

package com.marketplace.vintage.carrier;

import org.junit.Test;
import static org.junit.Assert.*;
import com.marketplace.vintage.carrier.ParcelCarrier;
import com.marketplace.vintage.carrier.ParcelCarrierFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParcelCarrierFactory_ESTest extends ParcelCarrierFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParcelCarrier parcelCarrier0 = ParcelCarrierFactory.createNormalParcelCarrier("XaePrice *;(1  axT*0.9");
      assertEquals("basePrice * (1 + tax) * 0.9", parcelCarrier0.getExpeditionPriceExpression());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParcelCarrier parcelCarrier0 = ParcelCarrierFactory.createPremiumParcelCarrier("XaePrice *;(1  axT*0.9");
      assertEquals("basePrice * (1 + tax) * 0.9", parcelCarrier0.getExpeditionPriceExpression());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParcelCarrierFactory parcelCarrierFactory0 = new ParcelCarrierFactory();
  }
}
