/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 20:11:35 GMT 2024
 */

package com.marketplace.vintage.persistent;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.marketplace.vintage.persistent.PersistentManager;
import java.io.File;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PersistentManager_ESTest extends PersistentManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockFile mockFile0 = new MockFile("KG~W#)Y/");
      PersistentManager persistentManager0 = new PersistentManager(mockFile0);
      FileSystemHandling.shouldAllThrowIOExceptions();
      persistentManager0.addReferenceToSave("BweE:/W,{gTIW-~qZk", "BweE:/W,{gTIW-~qZk");
      // Undeclared exception!
      try { 
        persistentManager0.save();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.IOException: Simulated IOException
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

  /*
  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PersistentManager persistentManager0 = new PersistentManager((File) null);
      PersistentManager.PersistentMap persistentManager_PersistentMap0 = new PersistentManager.PersistentMap();
      persistentManager0.addReferenceToSave("K", persistentManager_PersistentMap0);
      // Undeclared exception!
      try { 
        persistentManager0.save();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockFile mockFile0 = new MockFile("KG~W#)Y/");
      PersistentManager persistentManager0 = new PersistentManager(mockFile0);
      Map<String, Object> map0 = persistentManager0.loadPersistentData();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      File file0 = MockFile.createTempFile(" ?q>5NTWX^n,q_I.ebzN", " ?q>5NTWX^n,q_I.ebzN");
      PersistentManager persistentManager0 = new PersistentManager(file0);
      // Undeclared exception!
      try { 
        persistentManager0.loadPersistentData();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Corrupted binary
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MockFile mockFile0 = new MockFile("Hpon;}XP$G>7M!.L");
      PersistentManager persistentManager0 = new PersistentManager(mockFile0);
      // Undeclared exception!
      try { 
        persistentManager0.save();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // There is no data to save
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MockFile mockFile0 = new MockFile("com.marketplace.vintage.persistent.PersistentManager", "com.marketplace.vintage.persistent.PersistentManager");
      File file0 = MockFile.createTempFile("com.marketplace.vintage.persistent.PersistentManager", "com.marketplace.vintage.persistent.PersistentManager", (File) mockFile0);
      MockFile mockFile1 = new MockFile(file0, "com.marketplace.vintage.persistent.PersistentManager");
      PersistentManager persistentManager0 = new PersistentManager(mockFile1);
      persistentManager0.addReferenceToSave("com.marketplace.vintage.persistent.PersistentManager", "com.marketplace.vintage.persistent.PersistentManager");
      // Undeclared exception!
      try { 
        persistentManager0.save();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Could not create file
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MockFile mockFile0 = new MockFile("com.marketplace.vintage.persistent.PersistentManager", "com.marketplace.vintage.persistent.PersistentManager");
      PersistentManager persistentManager0 = new PersistentManager(mockFile0);
      persistentManager0.addReferenceToSave("com.marketplace.vintage.persistent.PersistentManager", "com.marketplace.vintage.persistent.PersistentManager");
      // Undeclared exception!
      try { 
        persistentManager0.save();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Error in writing to file
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      File file0 = MockFile.createTempFile("D[2+'cP')'Z-ADWZp", "D[2+'cP')'Z-ADWZp", (File) null);
      PersistentManager persistentManager0 = new PersistentManager(file0);
      persistentManager0.addReferenceToSave("D[2+'cP')'Z-ADWZp", "D[2+'cP')'Z-ADWZp");
      // Undeclared exception!
      try { 
        persistentManager0.save();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Error in writing to file
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

  /*
  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      PersistentManager persistentManager0 = new PersistentManager((File) null);
      // Undeclared exception!
      try { 
        persistentManager0.loadPersistentData();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.marketplace.vintage.persistent.PersistentManager", e);
      }
  }

   */
}
