/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 21:07:10 GMT 2024
 */

package com.marketplace.vintage.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.marketplace.vintage.exceptions.EntityNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EntityNotFoundException_ESTest extends EntityNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EntityNotFoundException entityNotFoundException0 = new EntityNotFoundException("");
  }
}
