/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun May 26 21:09:41 GMT 2024
 */

package com.marketplace.vintage.commands.item.stock;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ItemStockCommand_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.marketplace.vintage.commands.item.stock.ItemStockCommand"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\silva\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\silva\\Downloads\\trabalhos_POO 2\\trabalhos_POO\\TP3333"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\silva"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "silva"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ItemStockCommand_ESTest_scaffolding.class.getClassLoader() ,
      "com.marketplace.vintage.commands.user.UserInfoCommand",
      "com.marketplace.vintage.carrier.ParcelCarrierManager",
      "com.marketplace.vintage.view.BaseView",
      "com.marketplace.vintage.order.Order",
      "com.marketplace.vintage.commands.item.stock.ItemStockChangeCommand",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartCommand",
      "com.marketplace.vintage.carrier.ParcelCarrier",
      "com.marketplace.vintage.view.ViewFactory",
      "com.marketplace.vintage.stats.StatsManager",
      "com.marketplace.vintage.command.ParentCommand",
      "com.marketplace.vintage.utils.VintageDate",
      "com.marketplace.vintage.commands.stats.TopSellerStatsCommand",
      "com.marketplace.vintage.user.UserManager",
      "com.marketplace.vintage.commands.time.CurrentTimeCommand",
      "com.marketplace.vintage.commands.user.UserCommandUserView",
      "com.marketplace.vintage.input.InputPrompter",
      "impl.TshirtItem$TshirtItemPattern",
      "com.marketplace.vintage.commands.stats.StatsCommand",
      "com.marketplace.vintage.commands.item.stock.ItemStockCommand",
      "com.marketplace.vintage.commands.order.OrderReturnCommand",
      "com.marketplace.vintage.scripting.runner.ScriptRunner",
      "com.marketplace.vintage.expression.ExpressionSolver",
      "com.marketplace.vintage.item.ItemProperty",
      "com.marketplace.vintage.scripting.ScriptLoader",
      "com.marketplace.vintage.command.BaseCommand",
      "com.marketplace.vintage.exceptions.EntityAlreadyExistsException",
      "com.marketplace.vintage.logging.OnlyWarnLogger",
      "com.marketplace.vintage.commands.stats.TopListStatsCommand",
      "com.marketplace.vintage.order.OrderFactory",
      "com.marketplace.vintage.commands.HelpCommand",
      "com.marketplace.vintage.user.User",
      "com.marketplace.vintage.commands.item.ItemListAllCommand",
      "com.marketplace.vintage.order.OrderManager",
      "com.marketplace.vintage.view.CommandRunnerView",
      "com.marketplace.vintage.command.CommandManager",
      "com.marketplace.vintage.input.impl.StdinInputPrompter",
      "com.marketplace.vintage.logging.PrefixLogger",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartOrderCommand",
      "com.marketplace.vintage.command.CommandRepository",
      "com.marketplace.vintage.view.impl.UserView",
      "com.marketplace.vintage.commands.stats.BaseStatsCommand",
      "com.marketplace.vintage.commands.stats.VintageTotalStatsCommand",
      "com.marketplace.vintage.Vintage",
      "com.marketplace.vintage.order.OrderController",
      "com.marketplace.vintage.time.TimeManager",
      "com.marketplace.vintage.logging.Logger",
      "com.marketplace.vintage.expression.Exp4jExpressionSolver",
      "com.marketplace.vintage.logging.JavaLogger",
      "com.marketplace.vintage.item.ItemController",
      "com.marketplace.vintage.commands.order.OrderListCommand",
      "com.marketplace.vintage.scripting.ScriptController",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartAddItemCommand",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartRemoveItemCommand",
      "com.marketplace.vintage.item.ItemType",
      "impl.TshirtItem$TshirtItemSize",
      "com.marketplace.vintage.item.Item",
      "com.marketplace.vintage.commands.order.OrderCommand",
      "com.marketplace.vintage.item.condition.ItemCondition",
      "com.marketplace.vintage.scripting.exception.ScriptParseException",
      "com.marketplace.vintage.command.CommandExecuteException",
      "com.marketplace.vintage.order.OrderStatus",
      "com.marketplace.vintage.view.View",
      "com.marketplace.vintage.carrier.ParcelCarrierController",
      "com.marketplace.vintage.exceptions.EntityNotFoundException",
      "com.marketplace.vintage.scripting.exception.ScriptException",
      "com.marketplace.vintage.input.impl.BaseInputPrompter",
      "com.marketplace.vintage.command.Command",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartListCommand",
      "com.marketplace.vintage.user.UserController",
      "com.marketplace.vintage.commands.item.ItemCreateCommand",
      "com.marketplace.vintage.commands.LogoutCommand",
      "com.marketplace.vintage.commands.item.ItemListCommand",
      "com.marketplace.vintage.item.ItemFactory",
      "com.marketplace.vintage.commands.item.ItemCommand",
      "com.marketplace.vintage.item.ItemManager",
      "com.marketplace.vintage.commands.item.stock.ItemStockAddCommand",
      "com.marketplace.vintage.commands.item.stock.ItemStockRemoveCommand",
      "com.marketplace.vintage.commands.stats.TopParcelCarrierStatsCommand",
      "com.marketplace.vintage.commands.item.ItemInspectCommand"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ItemStockCommand_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.marketplace.vintage.command.ParentCommand",
      "com.marketplace.vintage.commands.item.stock.ItemStockCommand",
      "com.marketplace.vintage.command.BaseCommand",
      "com.marketplace.vintage.commands.HelpCommand",
      "com.marketplace.vintage.logging.JavaLogger",
      "com.marketplace.vintage.input.impl.BaseInputPrompter",
      "com.marketplace.vintage.input.impl.StdinInputPrompter",
      "com.marketplace.vintage.item.ItemFactory",
      "com.marketplace.vintage.item.ItemController",
      "com.marketplace.vintage.order.OrderManager",
      "com.marketplace.vintage.order.OrderFactory",
      "com.marketplace.vintage.order.OrderController",
      "com.marketplace.vintage.utils.VintageDate",
      "com.marketplace.vintage.item.ItemManager",
      "com.marketplace.vintage.logging.PrefixLogger",
      "com.marketplace.vintage.logging.OnlyWarnLogger",
      "com.marketplace.vintage.input.impl.BufferedInputPrompter",
      "com.marketplace.vintage.time.TimeManager",
      "com.marketplace.vintage.carrier.ParcelCarrierManager",
      "com.marketplace.vintage.carrier.ParcelCarrierController",
      "com.marketplace.vintage.expression.Exp4jExpressionSolver",
      "com.marketplace.vintage.user.UserManager",
      "com.marketplace.vintage.user.UserController",
      "com.marketplace.vintage.Vintage",
      "com.marketplace.vintage.stats.StatsManager",
      "com.marketplace.vintage.view.ViewFactory",
      "com.marketplace.vintage.view.BaseView",
      "com.marketplace.vintage.view.impl.UserView",
      "com.marketplace.vintage.scripting.ScriptController",
      "com.marketplace.vintage.scripting.ScriptLoader",
      "com.marketplace.vintage.exceptions.EntityNotFoundException",
      "com.marketplace.vintage.user.User",
      "com.marketplace.vintage.command.CommandManager",
      "com.marketplace.vintage.commands.LogoutCommand",
      "com.marketplace.vintage.commands.user.UserCommandUserView",
      "com.marketplace.vintage.commands.user.UserInfoCommand",
      "com.marketplace.vintage.commands.item.ItemCommand",
      "com.marketplace.vintage.commands.item.ItemCreateCommand",
      "com.marketplace.vintage.commands.item.ItemListCommand",
      "com.marketplace.vintage.commands.item.ItemInspectCommand",
      "com.marketplace.vintage.commands.item.ItemListAllCommand",
      "com.marketplace.vintage.commands.item.stock.ItemStockChangeCommand",
      "com.marketplace.vintage.commands.item.stock.ItemStockAddCommand",
      "com.marketplace.vintage.commands.item.stock.ItemStockRemoveCommand",
      "com.marketplace.vintage.commands.order.OrderCommand",
      "com.marketplace.vintage.commands.order.OrderListCommand",
      "com.marketplace.vintage.commands.order.OrderReturnCommand",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartCommand",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartAddItemCommand",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartRemoveItemCommand",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartListCommand",
      "com.marketplace.vintage.commands.shoppingcart.ShoppingCartOrderCommand",
      "com.marketplace.vintage.commands.time.CurrentTimeCommand",
      "com.marketplace.vintage.commands.stats.StatsCommand",
      "com.marketplace.vintage.commands.stats.BaseStatsCommand",
      "com.marketplace.vintage.commands.stats.TopSellerStatsCommand",
      "com.marketplace.vintage.commands.stats.TopParcelCarrierStatsCommand",
      "com.marketplace.vintage.commands.stats.VintageTotalStatsCommand",
      "com.marketplace.vintage.commands.stats.TopListStatsCommand",
      "com.marketplace.vintage.item.ItemFactory$1",
      "com.marketplace.vintage.item.Item",
      "impl.MalaItem",
      "impl.SapatilhasItem",
      "impl.PremiumSapatilhasItem",
      "com.marketplace.vintage.utils.AlphanumericGenerator",
      "impl.PremiumMalaItem",
      "com.marketplace.vintage.view.ViewFactory$1",
      "com.marketplace.vintage.view.impl.UserLoginView",
      "com.marketplace.vintage.commands.user.UserRegisterCommand",
      "com.marketplace.vintage.input.questionnaire.QuestionnaireBuilder",
      "com.marketplace.vintage.input.questionnaire.QuestionnaireQuestion",
      "com.marketplace.vintage.input.InputMapper",
      "com.marketplace.vintage.input.questionnaire.Questionnaire",
      "com.marketplace.vintage.item.ItemProperty",
      "com.marketplace.vintage.item.ItemType"
    );
  }
}
