/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun May 26 20:27:23 GMT 2024
 */

package com.marketplace.vintage.order;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Order_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.marketplace.vintage.order.Order"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\silva\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\silva\\Downloads\\trabalhos_POO 2\\trabalhos_POO\\TP3333"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\silva"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "silva"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Order_ESTest_scaffolding.class.getClassLoader() ,
      "com.marketplace.vintage.order.invoice.ParcelShipmentCostInvoiceLine",
      "impl.TshirtItem$TshirtItemPattern",
      "com.marketplace.vintage.order.OrderStatus",
      "com.marketplace.vintage.item.condition.ItemConditionType",
      "impl.PremiumMalaItem",
      "com.marketplace.vintage.item.condition.UsedItemCondition",
      "impl.PremiumSapatilhasItem",
      "com.marketplace.vintage.order.Order",
      "com.marketplace.vintage.item.ItemProperty",
      "impl.SapatilhasItem",
      "com.marketplace.vintage.item.Item$1",
      "impl.TshirtItem",
      "com.marketplace.vintage.order.invoice.ItemPriceInvoiceLine",
      "com.marketplace.vintage.utils.VintageDate",
      "com.marketplace.vintage.item.ItemType",
      "impl.TshirtItem$TshirtItemSize",
      "impl.MalaItem",
      "com.marketplace.vintage.order.invoice.InvoiceLine",
      "com.marketplace.vintage.item.Item",
      "com.marketplace.vintage.order.invoice.ItemSatisfactionInvoiceLine",
      "impl.TshirtItem$1",
      "com.marketplace.vintage.order.OrderedItem",
      "com.marketplace.vintage.item.condition.ItemCondition"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Order_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.marketplace.vintage.order.Order",
      "com.marketplace.vintage.order.OrderStatus",
      "com.marketplace.vintage.utils.VintageDate",
      "com.marketplace.vintage.order.invoice.InvoiceLine",
      "com.marketplace.vintage.order.invoice.ParcelShipmentCostInvoiceLine",
      "com.marketplace.vintage.item.condition.UsedItemCondition",
      "com.marketplace.vintage.item.Item",
      "impl.MalaItem",
      "impl.PremiumMalaItem",
      "com.marketplace.vintage.order.invoice.ItemSatisfactionInvoiceLine",
      "com.marketplace.vintage.order.invoice.ItemPriceInvoiceLine",
      "com.marketplace.vintage.order.OrderedItem",
      "impl.SapatilhasItem",
      "impl.PremiumSapatilhasItem",
      "com.marketplace.vintage.item.ItemType",
      "com.marketplace.vintage.item.Item$1",
      "impl.TshirtItem",
      "com.marketplace.vintage.item.condition.ItemConditionType",
      "impl.TshirtItem$1",
      "com.marketplace.vintage.item.ItemProperty"
    );
  }
}
